// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/romik1505/userDetailsService/internal/common"
)

type CreatePersonPayload struct {
	Status string `json:"status"`
}

type DeletePersonPayload struct {
	Status string `json:"status"`
}

type EditPersonPayload struct {
	Person *common.Person `json:"person"`
}
